### ISSUE TITLE
"Enter" shortcut is displayed for a table action which doesn't define it

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-security#100]
See User browser in a new project:
![image.png](https://images.zenhubusercontent.com/5aacbf4b4b5806bc2bcb3a01/949a35b2-e870-4784-b561-8c898b85bba9)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3433-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

![user-browser-context-menu](https://user-images.githubusercontent.com/85500330/129759850-f7e996dc-0b82-47ac-9e7b-0f2f24746d27.png)
