### ISSUE TITLE
"Enter" shortcut is displayed for a table action which doesn't define it (port to 1.0)

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-security#101]
See https://github.com/Haulmont/jmix-security/issues/100

See User browser in a new project:
![image.png](https://images.zenhubusercontent.com/5aacbf4b4b5806bc2bcb3a01/949a35b2-e870-4784-b561-8c898b85bba9)

**Comment by konyashkina** [comment]
Tested on:

- [x] Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3436-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

- [x] Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.0.1.SNAPSHOT3435-212
IntelliJ version: IntelliJ IDEA 2021.2 (Ultimate Edition)

Verified.
