### ISSUE TITLE
Change Password dialog doesn't check for any permissions

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#106]
- Create Jmix 1.0.1 project
- Create and assign role to the user that allows User READ and opening of user browser.
- Open application.

```

    @ScreenPolicy(screenIds = {"User.browse"})
    void screens();

    @EntityAttributePolicy(entityClass = User.class, attributes = "*", action = EntityAttributePolicyAction.VIEW)
    @EntityPolicy(entityClass = User.class, actions = EntityPolicyAction.READ)
    void user();
```

You can see that Edit and Remove is impossible, but you can change password of the other user without any problem:
![change-passw](https://user-images.githubusercontent.com/6158807/131370368-df15498b-0446-46e0-8487-30e70d1e1704.png)

![change-pass-2](https://user-images.githubusercontent.com/6158807/131370406-72c75861-f1de-465c-9e7b-b096a4c37920.png)

**Comment by alexbudarov** [comment]
the same with "reset remember me tokens" action

**Comment by knstvk** [comment]
Now all actions require EntityPolicyAction.UPDATE on the User entity.

**Comment by reznikova21** [comment]
Jmix version: 1.1.0-SNAPSHOT - verified
