### ISSUE TITLE
Incorrect screen route when opening built-in resource role for view

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#110]
Jmix: 1.0.0.

- Launch application
- Open ui-minimal role for view.
- Check screen route:

> http://localhost:8080/#main/7/resourceRoles/edit?id=new

![role-route](https://user-images.githubusercontent.com/6158807/133412657-441a7191-11e0-4a49-995d-9383edcb95ed.png)

Should be: something meaningful, e.g. "?code=ui-minimal".

Also if you restart the server and relogin, a weird empty screen is opened. Is it a bug that using a "/resourceRoles/edit?id=new" route leads to invalid screen instead of empty initialized editor?
![role-route-2](https://user-images.githubusercontent.com/6158807/133413553-e0a8d720-cb9d-4368-9aae-312b13c98b4c.png)

**Comment by Flaurite** [comment]
Wait for: https://github.com/Haulmont/jmix-ui/issues/760

**Comment by kendovitskii** [comment]
Verified on
1.2.0 - SNAPSHOT
