### ISSUE TITLE
Wrong cardinality at RowLevelPolicyEntity#role and ResourcePolicyEntity#role

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#116]
Version: latest master.

IDEA shows warning for RowLevelPolicyEntity#role and ResourcePolicyEntity#role attributes:
![image](https://user-images.githubusercontent.com/6158807/139411711-aa740654-09b4-408e-9e00-186a5d89affa.png)

![image](https://user-images.githubusercontent.com/6158807/139411917-d3ef7c02-5455-491d-b088-832941211e57.png)

**Comment by gorbunkov** [comment]
For QA: check that roles with policies are created without errors from the UI
