### ISSUE TITLE
Use function instead of predicate for row-level constraints

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-security#120]
Row-level predicates are serializable objects and may contain links in object fields to Application context or Spring beans.
It's hard to support the serialization of objects with spring specifics. it is not clear how it deserializes and requires custom logic over `readObject/writeObject`.

A possible solution would be to use the functions instead of predicates.
Functions arguments: 
- Application context. 
- Entity for in-memory constraint.

**Comment by knstvk** [comment]
Relates to #117

**Comment by gorbunkov** [comment]
New interface `RowLevelBiPredicate` has been introduced.

Predicates in row-level roles now can be defined in two ways. If you don't need to use Spring beans inside the function, the the role method should return `RowLevelPredicate`:

```java
@RowLevelRole(...)
public interface TestInMemoryRowLevelConstraintsRole {

    @PredicateRowLevelPolicy(entityClass = TestOrder.class, actions = {RowLevelPolicyAction.READ})
    static RowLevelPredicate<TestOrder> numberEndsWithB() {
        return (testOrder) -> testOrder.getNumber().endsWith("B");
    }
}
```

If Spring beans must be used in the function, then the method must return `RowLevelBiPredicate`:
```java
@RowLevelRole(...)
public interface TestInMemoryRowLevelConstraintsRole {

    @PredicateRowLevelPolicy(entityClass = TestOrder.class, actions = RowLevelPolicyAction.READ)
    default RowLevelBiPredicate<TestOrder, ApplicationContext> currentUserIsManager() {
        return (testOrder, applicationContext) -> {
            CurrentAuthentication currentAuthentication = applicationContext.getBean(CurrentAuthentication.class);
            UserDetails currentUser = currentAuthentication.getUser();
            return currentUser.equals(testOrder.getManager());
        };
    }
}

```

The first function argument here is the entity instance, the second argument is `ApplicationContext`.

For backward compatibility the following approach where Spring beans are passed as role method arguments should also work:

```java
@RowLevelRole(code = TestInMemoryRowLevelConstraintsMethodArgsRole.NAME, name = TestInMemoryRowLevelConstraintsMethodArgsRole.NAME)
public interface TestInMemoryRowLevelConstraintsMethodArgsRole {

    String NAME = "TestInMemoryRowLevelConstraintsMethodArgsRole";

    @PredicateRowLevelPolicy(entityClass = TestOrder.class, actions = RowLevelPolicyAction.READ)
    default RowLevelPredicate<TestOrder> numberEndsWithB(DataManager dataManager) {
        return (testOrder) -> {
            //use dataManager just to test that applicationContext may be used here
            List<ManyToOneEntity> allEntities = dataManager.load(ManyToOneEntity.class).all().list();
            return testOrder.getNumber().endsWith("B");
        };
    }
}
```
