### ISSUE TITLE
Display scope in tables with Resource roles

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#124]
Jmix: 1.1.0

Look screenshot. I don't understand which role scopes has this user, or has a role in the "Role assigments" screen.
Scope is important and should be displayed in all tables where resource roles are displayed.

![image](https://user-images.githubusercontent.com/6158807/141760878-72e68d38-40e7-4d0c-a298-8327cee353e9.png)

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
