### ISSUE TITLE
Hot deploy doesn't work properly while changing annotations

### ISSUE THREAD

**Issue by EvgeniiMamontov** [Haulmont/jmix-security#132]
**Steps:**

1. Create new project
2. Run app
3. Create new role
4. Change annotation from @ResourseRole to @RowLevelRole
5. Navigate to app ->Administration->Row-level roles tab

**ER:** Role should be shown

**AR:** Role doesn't show on Row-level roles tab

**Comment by gorbunkov** [comment]
I don't think that this is an often case and that it must solved on framework side. Developers don't often change roles annotations. And even they do so, it's not a big deal to restart an application in this case.
