### ISSUE TITLE
RoleAssignmentRepositoryImpl.getAllAssignments() returns duplicates

### ISSUE THREAD

**Issue by Rus226** [Haulmont/jmix-security#133]
the getAllAssignments () method of the io.jmix.security.impl.role.assignment.RoleAssignmentRepositoryImpl class, returns duplicates. Because the Collection assignmentProviders contains both individual providers and AllRoleAssignmentProviderImpl, and it, in turn, also contains all the providers

![96899ec6-31c1-4ae5-8d0d-6f23e0ed8b6c](https://user-images.githubusercontent.com/58604128/147063847-63ab7a5c-82cb-4e49-be20-ddd61b30d7fc.jpg)

**Comment by gorbunkov** [comment]
I didn't find the `AllRoleAssignmentProviderImpl` class in framework
