### ISSUE TITLE
Describe actions using Studio meta-annotations

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-security#134]
Jmix Studio highlights the following action types in screen descriptor:
1) ItemTrackingAction
2) ChangePasswordAction
3) ResetPasswordAction
4) ResetRememberMeTokenAction
5) ShowRoleAssignmentsAction
6) ShowUserSubstitutionsAction

![image](https://user-images.githubusercontent.com/35256248/147333597-c9aed2ed-e834-400a-b624-3f2aaf937210.png)

### QA
1) Check that Jmix Studio does not highlight the below action types
2) Check that the user can add the below actions using ComponentInspector
3) Check that the reference from type XML attribute to action class works correctly

**Comment by konyashkina** [comment]
_Tested on_ 
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT3983-213
IntelliJ version: IntelliJ IDEA 2021.3 (Ultimate Edition)
