### ISSUE TITLE
Enable removing design-time resource and row-level roles from provider caches

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-security#139]
Motivation: ability to remove some roles from security UI.

**Comment by gorbunkov** [comment]
For QA:

To test the issue you may inject `ResourceRoleRepository` and `RowLevelRoleRepository` to the main application class and remove some predefined role-level or resource roles when application is started. Removed roles should not be visible in roles browsers and should not be available for assignment to a user.

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
