### ISSUE TITLE
Localize BaseRoleModel

### ISSUE THREAD

**Issue by Flamesson** [Haulmont/jmix-security#140]
BaseRoleModel can be used in screens (f.e. in a Table). 
But it's attributes are not localized in messages

**Comment by gorbunkov** [comment]
BaseRoleModel's children (ResourceRoleModel and RowLevelRoleModel) are different entities with different behavior. Why do you need to them in a single table? What is your use case?

**Comment by aiden-izumi** [comment]
I need to display all user roles (name and code).
If I can't manage roles as an abstract thing, why inheritance?
