### ISSUE TITLE
For menu resource policies take into account both menu ids and menu screens

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-security#22]
A resource policy for menu item assumes that *resource* string is a menu item **id**. This oblige a developer to assign id to each menu item in the `menu.xml` file:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<menu-config xmlns="http://jmix.io/schema/ui/menu">
    <menu id="application" caption="msg://com.company.sample/menu.application" insertBefore="security">
        <item screen="sample_User.browse" caption="msg://com.company.sample.screen.user/UserBrowse.caption"/>
        <item screen="sample_Order.browse" caption="msg://com.company.sample.screen.order/orderBrowse.caption"/>
        <item id="sample_Customer.browse"
              screen="sample_Customer.browse"
              caption="msg://com.company.sample.screen.customer/customerBrowse.caption"/>
    </menu>
</menu-config>
```

By default, items are created without the **id** attribute. Only **screen** attribute is filled.

Probably the *resource* field of the resource policy may contain both id and screen values. The UI editor of the menu policy should display menu item id or screen.

**Comment by andreysubbotin** [comment]
For QA:
Create a role with a menu policy that references the menu item without the `id` attribute,  only with the screen attribute.
Check that role works as expected.
