### ISSUE TITLE
UI editor for screen resource policy should suggest to add a policy for corresponding menu item and vice versa

### ISSUE THREAD

**Issue by gorbunkov** [Haulmont/jmix-security#23]
When a resource policy is created for the screen, in the policy editor there must be a way to create a policy for corresponding menu item.
When a resource policy is created for a menu item, the editor should allow to add a policy for the screen.

**Comment by andreysubbotin** [comment]
Menu/screen policy create screen contains checkbox: grant access to screen/menu item. 
When the checkbox is enabled:
- Screen policy screen: system finds the corresponding menu item for the screen (by attribute `screen` in menu.xml) and creates 2 policies: for menu item and screen.
- Menu policy screen: system finds the corresponding screen for the menu (by attribute `screen` in menu.xml) and creates 2 policies: for menu item and screen.
