### ISSUE TITLE
Implement "Reset password" action

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-security#27]

**Comment by lovtsovaik** [comment]
Jmix version: 1.0.0-SNAPSHOT

**TC1**

1. Run the app
2. Open Users
3. Create some users (you may assign them the ui-minimal role + assess to change password window)
4. Select one or several users
5. Additional -> Reset passwords
6. Click OK ("Generate new random password" is unselected)

ER: The window is closing. Selected users see the "change password" window after successful login

AR: A new generated password is shown after every click OK. 
<img src="https://user-images.githubusercontent.com/73226373/113560404-00b05300-9614-11eb-954a-3a3d89df0f08.png" height="250" />

_____

**TC 2**
1-5. Do steps 1-5 from TC 1
6. Select  "Generate new random password" 
7. Click OK

ER: 
- After step 6 the generated passwords is shown as a table with logins. In CUBA it was like this:
<img src="https://user-images.githubusercontent.com/73226373/113561743-29d1e300-9616-11eb-95fc-a71b3dc569e7.png" height="300" />

- After step 7 the window should be closed

AR: 
- Generated passwords is shown not pretty. For 3 users only one login is shown with several passwords:
<img src="https://user-images.githubusercontent.com/73226373/113560471-1de52180-9614-11eb-859e-b72249798d16.png" height="250" />

- Window is not closed

Also, make dialog window wider for reading whole caption

**Comment by plakhov** [comment]
Fixed first TC.
New passwords will be shown in the text field because now we don't provide the opportunity to download table in excel format

**Comment by lovtsovaik** [comment]
Now the dialog window looks like this:
![image](https://user-images.githubusercontent.com/73226373/113980961-27f76200-9858-11eb-8786-4a09d233c626.png)

Problems:
1. Dialog window too small and we can not read whole caption -> make it wider
2. Checkbox "Generate new random password" is replaced by label "Generated passwords will be shown below", therefore we cannot choose the case where the user sets the password himself
3. Window is not closed by clicking OK, new passwords is generated instead

**Comment by plakhov** [comment]
1. Increase the width of the window.
2. If the user wants to set a new password for himself he should choose the "Change password" action.
3. For the closing window should use the "Close" button. I change the label to "Generated passwords will be shown below after clicking the "OK" button" also change the label for the "CLose" button

**Comment by lovtsovaik** [comment]
Please rename button "Ok" to "Generate and Save"

**Comment by lovtsovaik** [comment]
Generating new passwords looks good
![image](https://user-images.githubusercontent.com/73226373/114407897-f06f1980-9bb9-11eb-8154-b85dbafaf2f3.png)

Reset without generation is not implemented yet
