### ISSUE TITLE
User substitution

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-security#30]
#### Goal
Migrate user substitution functionality from CUBA (see CUBA docs)
#### Plan
- [x] (1d) list requirements considering CUBA implementation details
- [x] (sum:8d) Security logic:
     - [x] (4h) Learn Jmix security logic details
     - [x] (sum: 6d4h) Implementation itself
        - [x] (2d) Store substitution
        - [x] (sum: 4d) Spring security
           -  [x] (3d) Investigate
            - [x] (1d)Token and provider implementation
        - [x] (4h) Event
     - [x] (4h) Check and migrate usages in jmix-all      
     - [x] (4h) Refactor code, rework API
- [x] (sum: 3d) UI part:
   - [x] (1d) User substitution Browse/Edit screen
   - [x] (1d) UserIndicator: ability to select user from substituted using lookup field
   - [x] (4h) UserIndicator fixes: improve style, behaviour
   - [x] (4h) Main screen template: add substitution logic
- [x] (1d) Autotests

#### QA Notes:
Implemented mostly like in CUBA.
Unfinished parts placed inside related issues and Haulmont/jmix-security#111, Haulmont/jmix-ui#689
Use `Users->Additional->User substitutions to manage user substitutions`:
![изображение.png](https://images.zenhubusercontent.com/5ed6636766d0991824e90fb6/2db048f4-598e-4992-b959-499297df3b09)

**Comment by konyashkina** [comment]
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3625-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Google Chrome 94.0.4606.81, Firefox 93.0

Tested: 
- [x] User substitution Browse/Edit screen: CRUD (https://github.com/Haulmont/jmix-security/issues/112 )
- [x] unlimited substitution time, limited substitution time  
- [x] 1 substituted user, several substituted users
- [x] more than 1 substitution record for 1 user
- [x] no transitivity
- [x] switch to substituted user: substitution logic 
- [x] attributes permissions, screen permissions, specific permissions
- [x] BPM (My tasks, Start process screen)  
- [x] CurrentUserSubstitution interface
- [x] user sessions  
- [x] entity log
- [x] entity snapshots
- [x] user indicator 
- [x] theme settings for substituted user
- [x] table presentation for substituted user
- [x] localization (tested russian only)

no docs:  https://github.com/Haulmont/jmix-docs/issues/276
