### ISSUE TITLE
Brute force protection

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#32]
We had it in CUBA.
Looks like there is no OOB solution in spring.

Example implementation:
https://www.baeldung.com/spring-security-block-brute-force-authentication-attempts

> Nitpicking here, but you should probably use AtomicInteger for the counter. And really, you need to use a distributed counter because any app that you need to protect against brute force attacks is running in a cluster or at least on multiple machines.

**Comment by belyaev-andrey** [comment]
Just wonder if it may help: https://medium.com/teamarimac/implementing-throttling-in-java-spring-boot-ec4723cfce9f

**Comment by andreysubbotin** [comment]
- `jmix.security.bruteforceprotection.enabled` -  enables a mechanism for the protection against password brute force cracking. Default value: false
- `jmix.security.bruteforceprotection.blockInterval`- blocking interval in seconds after exceeding a maximum number of failed login attempts, if the `jmix.security.bruteforceprotection.enabled` property is on. Default value: 60 seconds


cuba.bruteForceProtection.maxLoginAttemptsNumber
A maximum number of failed login attempts for the combination of user login and IP address, if the cuba.bruteForceProtection.enabled property is on.

Default value: 5

Stored in the database.

Interface: ServerConfig

Used in the Middleware block.
