### ISSUE TITLE
Permitted IP mask

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#33]
Maybe it's not so important and widely used functionality, and not so complex to implement.

But to provide something for users migrating from CUBA we need at least:
- convenient extension point in authentication mechanism to check IP address before user login. Including REST API, or just web client??
- prepare sample project with implemented source IP mask checking.

**Comment by bulgakovea** [comment]
Implemented small sample application with the IP mask validation example.
https://github.com/jmix-projects/sample-ip-mask-jmix
