### ISSUE TITLE
Security scopes for REST, GraphQL and UI

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-security#35]
Like in CUBA.
Example: usage of UI Filter component requires READ permission to Filter entity. Then the user can load filters of all users in the system through REST.

--------------------------------------
In order to support separate security configurations for REST/GQL/UI, security scopes are introduced.
- The scope is configured for a resource role. it is possible to specify several security scopes for a role.
- There are 2 scopes: UI, API. REST and GQL always use  API scope. There is no ability to add new scopes or reconfigure scope for clients (UI, REST, etc) because they are hardcoded.
- Default scope value in Vaadin UI and Jmix Role designer is UI.
- Predefined roles (emailing, dynamic attributes, ..) should be configured for UI scope. FullAccessRole should work for all scopes: UI, API.
- Predefined roles are separated into 2 roles: backend and UI (which extends backend). A backend role most likely will be unused, so it is necessary to join roles into one.
- Authentication process: security scope is set to the authentication object while the user login into the system using LoggingForm or OAuth2 authentication endpoint. REST and GQL use the same OAuth2 authentication endpoint, so they have API scope and can't use different scopes.
- Authorization process: take into account scope from the authentication object and matches only with roles from the corresponding scope. 
- Row-level roles work without security scopes.

Samples for design-time roles: 
- Role for UI, API scopes (if no value is specified in `@ResourceRole` annotation):
```
@ResourceRole(code = EmailHistoryRole.CODE, name = "Email: read email history")
public interface EmailHistoryRole
```
- Role for UI scope:
```
@ResourceRole(code = EmailHistoryRole.CODE, name = "Email: read email history", scope = SecurityScope.UI)
public interface EmailHistoryRole
```

- Role for specified scopes:
```
@ResourceRole(code = FullAccessRole.CODE, name = "FullAccessRole", scope = {SecurityScope.UI, SecurityScope.API})
public interface FullAccessRole
```

TODO list: 
- [x] Runtime roles UI
- [x] Design time roles additional annotation attributes
- [x] Authentication process
- [x] Scope value in security model. Authorization process by scope 
- [x] Join predefined roles

**Comment by andreysubbotin** [comment]
Jmix Studio: https://youtrack.haulmont.com/issue/JST-1083

**Comment by maistrenkoIulia** [comment]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2775-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)
User with API scope role is allowed to view menu items

**Comment by andreysubbotin** [comment]
> User with API scope role is allowed to view menu items

Fixed

**Comment by maistrenkoIulia** [comment]
verified
