### ISSUE TITLE
Changing user's name doesn't affect role_assignment_entity changes

### ISSUE THREAD

**Issue by artemy63** [Haulmont/jmix-security#40]
Simple test case

1. Run empty Jmix project
2. Create new User with some username and assign him default 'system-full-access' role 
3. Edit created User
AR == ER:  Role assignment table shows one row with priviously selected role
4. Change username for given User
5. Edit User again
AR: no any assignment roles, table `sec_role_assignment_entity` contains rows with old username

As my understanding changing username should be consistent and shouldn't lead to missing inforamtion about assigned roles.

**Comment by andreysubbotin** [comment]
Username change should be denied because the username is the primary key for the user. Username change isn't allowed in mail accounts, google accounts.
