### ISSUE TITLE
Role assignments doesn't work properly

### ISSUE THREAD

**Issue by artemy63** [Haulmont/jmix-security#48]
I'm faced with some strange things for my point of view.

Test case 1
1. create new Jmix project based on 0.3.0-SNAPSHOT and run it (I'm choosing Postgres as main database)
2. create new User
3. create new role with some unique code and assign to created user
4. check DB state - table `sec_role_assignment_entity` contains proper mapping between username and rolecode
5. Go to role and modify its code - it is allowed right now - maybe should be disabled for editing?
6. check DB after modification - it keep the same `obsolete` data, row in  `sec_role_assignment_entity` points to not existed rolecode
7. If you go to user and click on 'Role assignments' it show incorrect data

Test case 2
Repeat steps 1-4 from test case 1
5. delete created role at all
6. check DB after deletion - it keep `obsolete` data, row in  `sec_role_assignment_entity` points to not existed rolecode
7. If you go to user and click on 'Role assignments' it show incorrect data

So clarify please what should be proper behavior of that:
- should be editing of role code disabled at all in near future?
- how will we synch changes in roles from UI (deleting as in TC2) with DB state?

**Comment by bulgakovea** [comment]
Now after removing a role, all assignments for that role are removed. 
The role code cannot be changed after the role is created.

**Comment by andreysubbotin** [comment]
couldn't find changes in 1.0

**Comment by maistrenkoIulia** [comment]
please, add a confirmation dialog screen in case role which user wants to removу шы assigned to at least one user

**Comment by andreysubbotin** [comment]
@maistrenkoIulia confirmation dialog message is unnecessary, role assignments are removed without interaction with UI when roles are removed.
