### ISSUE TITLE
Change error message when access is denied

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-security#51]
Jmix platform version: 0.3.0-SNAPSHOT

1. Run app
2. Administration -> Resource Roles
3. Create new role with access to menu but without access to the corresponding screen
4. Create user and give created role
5. Login with this user
6. Click menu item

AR: Access denied, but error is not clear for user
<img src="https://user-images.githubusercontent.com/73226373/107957241-c59d8600-6fb9-11eb-8ed8-f75f512f0492.png" height="200" />

ER: something with "Access denied"

**Comment by plakhov** [comment]
Now the message looks so ![Снимок экрана 2021-03-18 104009.png](https://images.zenhubusercontent.com/5f647fbb69c995706c8d74cc/514cdfec-9acd-45b9-8010-9214db5c070d)
