### ISSUE TITLE
Grant access to menu folders with access to menu items

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-security#52]
Imagine we have this application menu structure:
```
Application
    Users
    MyScreen
Administration
    Resource Roles
    ...
```
If create resource role with access to menu item only (e.g. "MyScreen"), the user will not see it.
If add access to folder ("Application"), user will see menu item inside the folder.

We need to simplify granting access to menu items, maybe automatically grant permission to all parent folders

**Comment by knstvk** [comment]
Let's do it at runtime when building menu: if the user has right to `MyScreen`, he is automatically granted rights to all its upper-level items like `Application`.
