### ISSUE TITLE
Groovy script in row-level predicate policy disappears after logout

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-security#56]
- Create a row-level role at runtime
- Add a row-level policy with a script, e.g. `!{E}.confidential`
- Save the policy and the role
- Open the role and the policy - the script is OK.
- Logout and login again, open the same policy - the script is empty.

**Comment by plakhov** [comment]
The bug fixed in the [ticket](https://app.zenhub.com/workspaces/jmix-5c76946ebe8f221bc5019e22/issues/haulmont/jmix-security/50)
