### ISSUE TITLE
Could not remove policy from databse stored Role

### ISSUE THREAD

**Issue by IskandarovRost** [Haulmont/jmix-security#64]
1) Open the Application->Resource roles screen
2) Create a new role
3) Add several policies 
4) Save the role
5) Open it again
6) Remove some policy by clicking "X Remove"
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/5600319d-72bc-4070-a5bd-a088101f2340)
*And it seems it was deleted*
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/ca02be51-609b-4bb9-bce6-a7733be071ab)
7) Click OK - save the role
8) Close and re-open the role browser (to ensure roles are re-loaded from database)
9) Open the edited role

**AR:** The policy is there again
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/0aa5f52a-1ae1-4c19-b972-21dc4db2d59a)

**Comment by knstvk** [comment]
See also #56
