### ISSUE TITLE
Add multiline description field to Roles

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#68]
Currently resource roles and row-level roles have "code" and "name" fields.
Code is expected to be used internally.
Name - to be shown in drop-down fields, in tables etc.

But "description" is still essential - a multi-line field where user can put some long notes about what this report does. A bit of documentation.

See examples:
- Report entity - has all 3 fields (code, name, description), and they proved to be useful (e.g. in Sherlock).
- AWS IAM roles - have multiline description:

![image](https://user-images.githubusercontent.com/6158807/112724225-c536ca00-8f2b-11eb-9686-5ff66489ba4b.png)

- YouTrack role - also has multiline description:
![image](https://user-images.githubusercontent.com/6158807/112724261-eeeff100-8f2b-11eb-9d7d-6affdfc883ae.png)

**Comment by lovtsovaik** [comment]
For QA: also create ticket on jmix studio (role designer)

**Comment by alexbudarov** [comment]
https://youtrack.jmix.io/issue/JST-1058
