### ISSUE TITLE
SystemAuthentication doesn't work correctly

### ISSUE THREAD

**Issue by Desire456** [Haulmont/jmix-security#69]
Check https://github.com/Haulmont/jmix-email/issues/30. 
Emailer#processQueuedEmails() invokes SystemAuthentication#begin() and then SystemAuthentication#end() method. 
After invoking processQueuedEmails() you can't open any screen with error message "Access denied".
![image](https://user-images.githubusercontent.com/49342498/112802964-dbf03480-9083-11eb-98d6-ca787a9e4f53.png)I

**Comment by knstvk** [comment]
Fixed in Haulmont/jmix-core#129
