### ISSUE TITLE
@PredicateRowLevelPolicy preventing DELETE doesn't work

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#71]
test project:
[jrlvl.zip](https://github.com/Haulmont/jmix-security/files/6220833/jrlvl.zip)

There is a row-level policy preventing modification and deletion of Account with author not equal to current user:
com.company.jrlvl.security.SiteUserRowLevelRole
```
    @PredicateRowLevelPolicy(
            entityClass = Account.class,
            actions = {RowLevelPolicyAction.UPDATE, RowLevelPolicyAction.DELETE}
    )
    default Predicate<Account> deckCanBeChanged(CurrentAuthentication currentAuthentication) {
        return deck -> {
            UserDetails details = currentAuthentication.getUser();
            if (details instanceof User) {
                User user = (User) details;
                return user.equals(deck.getAuthor());
            }
            return false;
        };
    }
```

It works for update, but is not called for delete.

- launch project
- create user "test"
- assign roles for him: UI-minimal, SiteUser (resource), SiteUser (row level)
- create Account with author = admin
- login with "test"
- try to edit admin's Account - it is prohibited
- now try to remove admin's Account

Expected:
not allowed

Actual:
admin's Account is removed

**Comment by maistrenkoIulia** [comment]
verified
