### ISSUE TITLE
Support hot-deploy for design-time role definitions

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#72]
**Motivation**
Implementing and debugging design-time role definitions is a tedious task.
Like below:
- launch app
- login with test user with assigned role (in development)
- try to reach necessary function
- get "access denied"
- add one more permission
- restart app, wait for server start
...
- login with test user
- try to reach necessary function
- get "access denied"
- add one more permission
- restart app, wait for server start
...
It would be a great usability improvement of the development process if changes in design-time role definitions were caught instantly by the application.

**What to do**
- Add support for hot-deploying role definitions.
- Add new or use existing flag to disable such ability in production environment - as a dangerous behavior for production environment

**Comment by artemglinov** [comment]
## Progress

2021-08-10: 20%

- [] Analyze, discuss (3d)
- [] Add and test hot deploy logic in AnnotatedResourceRoleProvider (4d)
- [] Add and test hot deploy logic to AnnotatedRowLevelRoleProvider (2d)
- [] Add flag to disable hot deploy of design-time roles (?)
