### ISSUE TITLE
Extra elements are present for "Resource" field in "Create screen resource policy" window

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-security#73]
#### Environment
Jmix version: 1.0.0-SNAPSHOT

#### Test case

1. Run any project 
2. Open Administration > Resource roles
3. Click Create
4. Click Create > Screen policy
5. Look at the list of suggested items for Resource field

#### AR
Extra elements are present, such as message keys
![image](https://user-images.githubusercontent.com/73226373/113095417-6f507380-9204-11eb-8adc-f66a540be967.png)

#### ER
Only screens
And may be show code in the brackets like for entities?
![image](https://user-images.githubusercontent.com/73226373/113095967-817ee180-9205-11eb-97d0-d4a110d7b409.png)

**Comment by andreysubbotin** [comment]
Fragments removed. `inputDialog` - is a valid screen item in the options list.
