### ISSUE TITLE
`RoleGrantedAuthority.getAuthority()` returns empty string for row-level roles

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-security#77]
![image.png](https://images.zenhubusercontent.com/5aacbf4b4b5806bc2bcb3a01/b366ab0b-f2ff-4ef7-8bf9-9c79b99ad8a2)

**Comment by andreysubbotin** [comment]
Is it a bug? We can use role code only for debugging purposes. `GrantedAuthority#getAuthority` should always return `null` for RL roles -> RL roles don't take into account spring security `hasRole` method aspects.

**Comment by knstvk** [comment]
There is a minor problem with `GrantedAuthority#getAuthority` returning null - when using `User.builder()` in tests, it doesn't allow to set more than one row-level role for a user. See `org.springframework.security.core.userdetails.User#sortAuthorities` and `org.springframework.security.core.userdetails.User.AuthorityComparator` - it sorts by `getAuthority()` which is the same empty string for all row-level rows and thus `sortedAuthorities` set contains only the first role.
