### ISSUE TITLE
Enable OAuth2 security for custom endpoints by default

### ISSUE THREAD

**Issue by belyaev-andrey** [Haulmont/jmix-security#78]
Probably we should agree on a path that will be secured. E.g. all endpoints deployed to `api/rest/**` are protected by OAuth2 and `api/public/**` are available for anonymous access.

**Comment by andreysubbotin** [comment]
Changes:
https://github.com/Haulmont/jmix-rest/commit/9f552e8209f2f493fccdfd1c472fc9d512665be2
https://github.com/Haulmont/jmix-security/commit/a53391e9502264eb53ef8e828226a6e8b4e4903b
https://github.com/Haulmont/jmix-reports/commit/7af7b29a63b30e5183574cb040be9d1e9edbc9e4
https://github.com/Haulmont/jmix-bpm/commit/4b6b5b61e9633a3208eb3079e98f3f0f40318d38

**Comment by andreysubbotin** [comment]
Endpoints deployed to `/rest/**` are available for authenticated access and `rest/public/**` are available for anonymous access.
URLs for Reports and BPM endpoints changed:
- from `/bpm/api` to `/rest/bpm`
- from `/reports/api` to `/rest/reports`
