### ISSUE TITLE
Unable to add a screen policy if two screens with the same caption exist

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-security#80]
Project: [testapp.zip](https://github.com/Haulmont/jmix-security/files/6317915/testapp.zip)
There are two different screens with the same caption in the project: EmployeeBrowse and EmployeeScreen.

Steps to reproduce:
1. Open Administration -> Resource roles
2. Click on the "Create" button
3.  Try to add a screen policy
AR:
![image](https://user-images.githubusercontent.com/71265042/114869992-b182d300-9e08-11eb-9aa9-c8e45951b7f1.png)

**Comment by maistrenkoIulia** [comment]
verified
