### ISSUE TITLE
NPE after removing the policy in a new resource role

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-security#81]
Project: [test.zip](https://github.com/Haulmont/jmix-security/files/6318062/test.zip)

Steps to reproduce:
1. Open Administration -> Resource roles
2. Click on the "Create" button
3. Create any policy
4. Remove the created policy
AR: Policy is removed, but NPE is thrown
![image](https://user-images.githubusercontent.com/71265042/114872560-851c8600-9e0b-11eb-9fcb-38e8087eecaf.png)

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-security#83

**Comment by maistrenkoIulia** [comment]
verified
