### ISSUE TITLE
It is impossible to configure `Screen policy` in case there is two screens with the same caption

### ISSUE THREAD

**Issue by artemy63** [Haulmont/jmix-security#84]
When we trying to create new screen policy the next code is called - https://github.com/Haulmont/jmix-security/blob/master/security-ui/src/main/java/io/jmix/securityui/screen/resourcepolicy/ResourcePolicyEditorUtils.java#L107-L120
In case in the system there is more than one screen with the same caption it will produce exception.
By my point of view customer can easily configure such case and we need to rework this behavior somehow or document it.

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-security#80
