### ISSUE TITLE
merge sec_row_level_role and sec_resource_role into one role table

### ISSUE THREAD

**Issue by khoshbin** [Haulmont/jmix-security#91]
Hi there
  Because we need to use the security sub system in other microservices  , it is better to merge two sec_resource_role and sec_row_level_role into one sec_role table-simpler is better.
Idealy it is better to merge sec_resource_policy and sec_row_level_policy into one sec_policy  or sec_permission table.
I think single table inheritance is better approach in this regard.

Thanks

**Comment by alexbudarov** [comment]
We are sorry but we can't make breaking changes in the data model just because it would be more convenient for your custom purposes.

Note that "security" module is optional and detachable in Jmix. You can fork the module and implement your own security system for your application if you need.

**Comment by khoshbin** [comment]
@alexbudarov I think our use case is common use case in microservices era. Your security system should be simple & accessible for other services.
we can handle it for our project , but I can't judge the cost of this complexity  in database layer . You can use  application level separation.
Regards

**Comment by alexbudarov** [comment]
@khoshbin 
Sorry, but I don't understand how merging two tables into one table will help with microservices.
These two tables contain different kinds of data, and if you receive the roles from external source in your project, you'll need to distinguish them anyway.

If you think your case is a common one, you are welcome to post your case in a more detailed form to a forum which is more suitable for discussion: https://forum.jmix.io/
We will consider how Jmix can help (maybe an addon, integration with existing Boot module etc.).
