### ISSUE TITLE
Ability to assign permissions for custom GraphQL resolvers

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-security#93]
### Progress
27-07-21: 10%
28-07-21: 20%
29-07-21: 35%
02-08-21: 75%
05-08-21: 100%

- [x] investigate the issue
- [x] create @GraphQLPolicy annotation and implement parameter handling and saving
- [x] create an GUI for manipulating access
- [x] implements protection mechanism
- [x] provide GraphQLAnonymousAccess annotation
- [x] improve compatibility with projects. minor improvements

### Usage
Now all custom queries protected by its own permission.

> E.g. one role can call GraphQL endpoints A and B, but not C.
> Another role can call GraphQL endpoints B and C, but not A.

#### Policy

@GraphQLPolicy annotation is used to control access to requests - place string or string array with query name in annotation value to give access to the relevant query.

Example of policy with access to all queries
```
    @GraphQLPolicy(operations = "*")
    void fullAccess();
```
FullAccessRole contains this permission by default.

Example of policy with access to specific queries
```
    @GraphQLPolicy(operations = {"testQuery1","testQuery2"})
    public void testRole();
```

Also permission to operation can be added from Resource Role editor screen.

#### Access

All custom graphQL queries and mutations protected by default. To allow anonymous access to the specified operation, you need to add a role with access to graphQL and requests for the anonymous user.

```
    @Override
    protected void initAnonymousUser(User anonymousUser) {
        Collection<GrantedAuthority> authorities = getGrantedAuthoritiesBuilder()
                .addResourceRole(GraphQLMinimalRole.CODE)
                .addResourceRole("operation_access_role")
                .build();
        anonymousUser.setAuthorities(authorities);
    }
```

#### Access check

Before the operation is performed, a check will be made for access to it. If there are several operations in one request and at least one of which will be custom and there will be no access to it, the operation will be canceled. 

relates to https://github.com/Haulmont/jmix-graphql/issues/41

**Comment by alexbudarov** [comment]
- custom graphql endpoints should be deny-by-default
- use "anonymous" user in GraphQL for custom endpoints that should be accessible without authentication
- use graphql endpoint name as ID for security settings (ask Vlad how to determine it)
- create new security policy for GraphQL endpoints
- support graphql permissions in runtime role editor and in Studio's resource role designer
- Studio will help with renaming associated elements in code if developer renames GraphQL custom endpoint method with Shift + F6

**Comment by bulgakovea** [comment]
Access to GraphQL will be declared via the _@SpecificPolicy_ annotation.

For anonymous access, we will implement _@GraphQLAnonimousAccess_ on a method or bean.

To solve the security issue, we need to get all custom non-CRUD endpoints. To do this, we get all the beans with the _@GraphQLApi_ annotation and check access to the corresponding endpoint before method invoking.

It is necessary to determine exactly how to associate the name of the method and the name of the endpoint. This is necessary for the implementation of 

> * use graphql endpoint name as ID for security settings
