### ISSUE TITLE
Add ability to store timezone on a user

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-security#97]
https://forum.jmix.io/t/how-to-set-user-timezone/314/7

- Add `HasTimeZone` interface with `getTimeZone` method. If User entity implements `HasTimeZone`, Jmix framework (`CurrentAuthentication#getTimeZone`) should use timezone from a User entity for all datetime operations.
- Scaffold User entity and UI with timezone.

**Comment by knstvk** [comment]
Probably `HasTimeZone` would be a better name.

**Comment by andreysubbotin** [comment]
QA Notes:
User UI contains the TimeZone field. If the TimeZone field is empty, timeZone is detected by the web browser.
UI Date components take into account user timezone.

**Comment by reznikova21** [comment]
Jmix version: 1.1.0-SNAPSHOT - verified
