### ISSUE TITLE
Extract logic from ChangePasswordAction to be able to use it in custom actions

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-security#98]
Motivation: see [forum topic](https://forum.jmix.io/t/help-for-roles-and-permissions/353).

----
### Changes
Now `ChangePasswordDialog` is a screen that is created by `ChangePasswordAction`.

`ChangePasswordDialog` can be used separately from action and can be created by `Screens`.

Screen can be configured by setting user (inherited from UserDetails) and currentPasswordRequired option.

For instance:
```
screens.create(ChangePasswordDialog.class)
        .withUsername(username)
        .withCurrentPasswordRequired(true)
        .show();
```

Added new message keys:
```
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.currentPasswordRequired=Current password can not be blank
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.confirmPasswordRequired=Confirmed password can not be blank
```

### Breaking changes
The following message keys:
```
changePasswordDialog.currentPassword
changePasswordDialog.password
changePasswordDialog.passwordRequired
changePasswordDialog.confirmPassword
changePasswordDialog.captionWithUserName
changePasswordDialog.wrongCurrentPassword
changePasswordDialog.currentPasswordWarning
changePasswordDialog.passwordsDoNotMatch
changePasswordDialog.passwordChanged
```
Are changed:
```
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.currentPassword
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.password
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.passwordRequired
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.confirmPassword
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.captionWithUserName
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.wrongCurrentPassword
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.currentPasswordWarning
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.passwordsDoNotMatch
io.jmix.securityui.screen.changepassword/ChangePasswordDialog.passwordChanged
```
### QA
1. Make sure that changing password works and validation is correct.
2. In the `user-browse.xml` in your project add parameter to the `changePassword` action:
```
<action id="changePassword" type="changePassword">
    <properties>
        <property name="currentPasswordRequired" value="true"/>
    </properties>
```
try to change password and check validation.
3. Your cases.

**Comment by owlet1997** [comment]
**TC:**
new passwords are equal with current

**AR:**
notification style is WARNING:
![image](https://user-images.githubusercontent.com/45730069/137896873-a2e5dcdb-8e86-4993-98a6-1d3105124321.png)
 
**ER**
style should be the same with other notific
![image](https://user-images.githubusercontent.com/45730069/137897005-3305b224-1acd-4185-a34d-617d24f1c77a.png)
ations:
